package vpplugins.packagespecgenerator.codegenerators;

import vpplugins.packagespecgenerator.adapters.OracleDbPackageAdapter;
import vpplugins.packagespecgenerator.model.enums.AccessModifier;
import vpplugins.packagespecgenerator.model.enums.ModelStereotypes;
import vpplugins.packagespecgenerator.model.objects.OracleDbFunction;
import vpplugins.packagespecgenerator.model.objects.OracleDbPackage;
import vpplugins.packagespecgenerator.model.objects.OracleDbProcedure;
import vpplugins.packagespecgenerator.model.objects.OracleDbSubProgram;
import vpplugins.packagespecgenerator.model.objects.OracleDbSubProgramParameter;
import vpplugins.packagespecgenerator.model.objects.OracleDbVariable;
import vpplugins.packagespecgenerator.util.CodeFormattingUtils;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Map.Entry;
import org.apache.log4j.Logger;

public class PackageSpecGenerator extends CommonCodeGenerator {
   static final Logger log = Logger.getLogger(PackageSpecGenerator.class);

   @SuppressWarnings("unchecked")
   public String getCode(OracleDbPackageAdapter adapter) {
      OracleDbPackage oracleDbPackage = adapter.getOracleDbPackage();
      boolean isDbPackage = (oracleDbPackage.getSpecialStereoTypeName() == ModelStereotypes.ORACLE_DB_PACKAGE.getStereotype());
      boolean includeInitBuffer = false;

      StringBuffer codeHeaderBuffer = new StringBuffer();
      StringBuffer codeBuffer = new StringBuffer();
      StringBuffer initBuffer = new StringBuffer();

      @SuppressWarnings("rawtypes")
      List parameterList = new ArrayList();

      if (!isDbPackage) { 
         codeHeaderBuffer.append("\n/*\n");
         codeHeaderBuffer.append("\n  There is no specification, since all code is standalone.\n");
         codeHeaderBuffer.append("\n*/\n");
         return codeHeaderBuffer.toString();
      } else {
         codeHeaderBuffer.append("create or replace package " + oracleDbPackage.getFullyQualifiedName());
         codeHeaderBuffer.append("\nas");

         if (oracleDbPackage.getDescription() != null && oracleDbPackage.getDescription().toString().length() >  0) {
            codeHeaderBuffer.append("\n      /*\n");
            codeHeaderBuffer.append(CodeFormattingUtils.docWordWrap(oracleDbPackage.getDescription(), 120, 8));
            codeHeaderBuffer.append("\n      */\n");
         }

         String s1 =
            "Generated by \"OraDbCodeGen\", a Visual Paradigm plugin that allows database code to be modeled using UML Class diagram models. "+
            "Implements a \"data-interface\", allowing upstream systems (such as middlware backends) to access specific data sets without exposing "+
            "any part of the underlying data model.  Instead of direct access to any database tables, \"ref-cursor\" functions are provided that "+
            "return ref-cursors.  This implementation keeps the database query logic private from any upsteam systems. "+
            "\n\n"+
            "Ref-cursors work with coding languages that do not require strong typing, such as Java, Go, etc.  When the upstream system is another "+
            "database system, such as over a database link, strongly-typed access is needed (ref-cursors do not work over database links).  For each "+
            "\"ref-cursor\" function, a set of wrapper functions are provided that allow for \"strongly-typed\" access."+
            "\n\n"+
            "\"OraDbCodeGen\" automates the creation of the \"ref-cursor\" functions and their \"strongly-typed\" wrapper functions by generating "+
            "database code from a UML class model.  The UML class model must implement certain specific conventions and stereotypes as the means of "+
            "specifying \"ref-cursor\" functions.  \"OraDcCodeGen\" also allows the generation of generic procs, functions and packages that do not "+
            "need to implement a \"data-interface\" for upstream systems. "+
            "\n\n"+
            "Asides from the utility of the \"ref-cursor\" and \"stongly-typed\" wrapper functionality offered by \"OraDbCodeGen\", creating a UML "+
            "model of one's database code is a practice that has significant advantages: "+
            "\n\n"+
            "  1. Speeds up the process of developing and maintaining database code (yes, detailed documentation - especially up "+
            "     front - speeds things up).\n\n"+
            "  2. Class diagram models provide an excellent, and very granular form of specification, allowing the code's designers "+
            "     to communicate to the code's developers what to code.\n\n"+
            "  3. Allows the concerns of the code's designers (what procs and functions are needed, what should their arguments be, how do they "+
            "     interact with one another) to be separated from the concerns of the code's developers (what is the best code to achieve "+
            "     the functionality).\n\n"+
            "  4. UML class models of database code are visually compact, and easy to work with.  They allow code designers to model "+
            "     code bases that can get very large, consisting of hundreds or thousands of procedures and functions.  It is a simple matter "+
            "     to maintain one version of the model representing the current state of the code, and other versions representing future "+
            "     states of the code, which form the specifications that developers later use to change the code.\n\n"+
            "\n"+
            "So using UML models of database code have their advantages.  Creating those models in Visual Paradigm, together with using the "+
            "\"OraDbCodeGen\" plugin has further advantages, over and above the \"data-interface\" capabilities:"+
            "\n\n"+
            "  5. When a UML class model is used in conjunction with a plugin like this one, an initial 'stub' of the code can be generated "+
            "     from the model in seconds, giving developers a headstart.\n\n"+
            "  6. Generating the initial code from a model allows the element descriptions in the model to be included as \"documentation\" "+
            "     within the generated code.\n\n"+
            "  7. Documentation can be generated from the model.  In particular, Visual Paradigm allows for HTML and MS-word forms of models "+
            "     to be generated.  Publishing a HTML form of the class models of databse code is a great way of maintaining code documentation, "+
            "     without having to trouble developers.\n\n"
         ;
         initBuffer.append("\n      /*\n"+CodeFormattingUtils.docWordWrap(s1, 100, 8)+"      */\n");

         @SuppressWarnings("rawtypes")
         Iterator subPrograms = oracleDbPackage.getPackageVariables().entrySet().iterator();

         while(subPrograms.hasNext()) {
            @SuppressWarnings("rawtypes")
            Entry<OracleDbVariable, AccessModifier> entry = (Entry)subPrograms.next();
            AccessModifier packageVariableAccessModifier = (AccessModifier)entry.getValue();
            if (packageVariableAccessModifier == AccessModifier.PUBLIC) {
               OracleDbVariable packageVariable = (OracleDbVariable)entry.getKey();
               if (!packageVariable.getDescription().isEmpty()) {
                  codeBuffer.append("\n  -- " + packageVariable.getDescription().replace("\n", "\n  --"));
               }

               codeBuffer.append("\n  " + packageVariable.getName() + " " + packageVariable.getDataType());
               if (!packageVariable.getDefaultValue().isEmpty()) {
                  codeBuffer.append(" := " + CodeFormattingUtils.wrapLiteralValueByDataType(packageVariable.getDefaultValue(), packageVariable.getDataType()));
               }

               codeBuffer.append(";\n");
            }
         }

         subPrograms = oracleDbPackage.getSubPrograms().iterator();

         while(true) {
            OracleDbSubProgram subProgram;
            OracleDbFunction currentFunction;
            do {
               do {
                  do {
                     if (!subPrograms.hasNext()) {
                        codeBuffer.append("\n");
                        subPrograms = oracleDbPackage.getSubPrograms().iterator();

                        while(subPrograms.hasNext()) {
                           subProgram = (OracleDbSubProgram)subPrograms.next();
                           if (subProgram instanceof OracleDbFunction && ((OracleDbFunction)subProgram).getReturnRefCursor() != null) {
                              currentFunction = (OracleDbFunction)subProgram;
                              codeBuffer.append(super.generateRecordAndTableTypesForRefCursor(currentFunction.getReturnRefCursor(), currentFunction));
                           }
                        }

                        // codeBuffer.append("\n");
                        initBuffer.append("\n" + this.generateInitProc(oracleDbPackage, false));
                        subPrograms = oracleDbPackage.getSubPrograms().iterator();

                        while(true) {
                           while(true) {
                              do {
                                 if (!subPrograms.hasNext()) {
                                 codeBuffer.append("\n\nend;\n/\n");
                                 if (includeInitBuffer) {
                                    codeHeaderBuffer.append(initBuffer);
                                 }
                                 return codeHeaderBuffer.toString()+codeBuffer.toString();
                                 }

                                 subProgram = (OracleDbSubProgram)subPrograms.next();
                              } while(subProgram.getAccessModifier() == AccessModifier.PRIVATE);

                              if (subProgram.getAccessModifier() == AccessModifier.PUBLIC && subProgram instanceof OracleDbFunction && ((OracleDbFunction)subProgram).getReturnRefCursor() != null) {
                                 currentFunction = (OracleDbFunction)subProgram;
                                 includeInitBuffer=true; 
                                 codeBuffer.append(super.generateStFunctionCode(currentFunction, false, false));
                                 codeBuffer.append(super.generateStFunctionCode(currentFunction, true, false));
                              }

                              if (subProgram instanceof OracleDbProcedure) {
                                 codeBuffer.append(super.generateProcedureCode((OracleDbProcedure)subProgram, false, !isDbPackage, oracleDbPackage.getOwningSchema()));
                              } else if (subProgram instanceof OracleDbFunction && ((OracleDbFunction)subProgram).getReturnRefCursor() != null) {
                                 codeBuffer.append(super.generateFunctionCode(oracleDbPackage, (OracleDbFunction)subProgram, false, false, true, !isDbPackage, oracleDbPackage.getOwningSchema()));
                                 if (subProgram.getParameters().size() != 0) {
                                    codeBuffer.append(super.generateFunctionCode(oracleDbPackage, (OracleDbFunction)subProgram, true, false, true, !isDbPackage, oracleDbPackage.getOwningSchema()));
                                 }
                              } else if (subProgram instanceof OracleDbFunction) {
                                 codeBuffer.append(super.generateFunctionCode(oracleDbPackage, (OracleDbFunction)subProgram, false, false, false, !isDbPackage, oracleDbPackage.getOwningSchema()));
                              }
                           }
                        }
                     }

                     subProgram = (OracleDbSubProgram)subPrograms.next();
                  } while(subProgram.getAccessModifier() != AccessModifier.PUBLIC);
               } while(!(subProgram instanceof OracleDbFunction));
            } while(((OracleDbFunction)subProgram).getReturnRefCursor() == null);

            currentFunction = (OracleDbFunction)subProgram;

            for(int i = 0; i < currentFunction.getParameters().size(); ++i) {
               OracleDbSubProgramParameter parameter = (OracleDbSubProgramParameter)currentFunction.getParameters().get(i);
               if (parameterList.indexOf(parameter.getName()) == -1) {
                  parameterList.add(parameter.getName());
                  String DataType = parameter.getDataType();
                  if (DataType.equals("varchar2") || DataType.equals("varchar")) {
                     DataType = DataType + "(4000)";
                  }

                  // codeBuffer.append("\n  " + parameter.getName().replaceFirst("p", "g") + CodeFormattingUtils.Spacer(30, parameter.getName().length()) + DataType + " := null;");
                  codeBuffer.append("\n  " + parameter.getName().replaceFirst("p", "g") + CodeFormattingUtils.rPad( DataType,30) + " := null;");
               }
            }
         }

      }
   }
}
