create or replace package xxschema."xxpub2"
as
      /*
        Some description of the package's purpose
      */

      /*
        Generated by "OraDbCodeGen", a Visual Paradigm plugin that allows database code to be modeled using
        UML Class diagram models. Implements a "data-interface", allowing upstream systems (such as
        middlware backends) to access specific data sets without exposing any part of the underlying data
        model. Instead of direct access to any database tables, "ref-cursor" functions are provided that
        return ref-cursors. This implementation keeps the database query logic private from any upsteam
        systems.

        Ref-cursors work with coding languages that do not require strong typing, such as Java, Go, etc.
        When the upstream system is another database system, such as over a database link, strongly-typed
        access is needed (ref-cursors do not work over database links). For each "ref-cursor" function, a
        set of wrapper functions are provided that allow for "strongly-typed" access.

        "OraDbCodeGen" automates the creation of the "ref-cursor" functions and their "strongly-typed"
        wrapper functions by generating database code from a UML class model. The UML class model must
        implement certain specific conventions and stereotypes as the means of specifying "ref-cursor"
        functions. "OraDcCodeGen" also allows the generation of generic procs, functions and packages that
        do not need to implement a "data-interface" for upstream systems.

        Asides from the utility of the "ref-cursor" and "stongly-typed" wrapper functionality offered by
        "OraDbCodeGen", creating a UML model of one's database code is a practice that has significant
        advantages:

          1. Speeds up the process of developing and maintaining database code (yes, detailed documentation -
          especially up front - speeds things up).

          2. Class diagram models provide an excellent, and very granular form of specification, allowing the
          code's designers to communicate to the code's developers what to code.

          3. Allows the concerns of the code's designers (what procs and functions are needed, what should
          their arguments be, how do they interact with one another) to be separated from the concerns of the
          code's developers (what is the best code to achieve the functionality).

          4. UML class models of database code are visually compact, and easy to work with. They allow code
          designers to model code bases that can get very large, consisting of hundreds or thousands of
          procedures and functions. It is a simple matter to maintain one version of the model representing
          the current state of the code, and other versions representing future states of the code, which
          form the specifications that developers later use to change the code.


        So using UML models of database code have their advantages. Creating those models in Visual
        Paradigm, together with using the "OraDbCodeGen" plugin has further advantages, over and above the
        "data-interface" capabilities:

          5. When a UML class model is used in conjunction with a plugin like this one, an initial 'stub' of
          the code can be generated from the model in seconds, giving developers a headstart.

          6. Generating the initial code from a model allows the element descriptions in the model to be
          included as "documentation" within the generated code.

          7. Documentation can be generated from the model. In particular, Visual Paradigm allows for HTML
          and MS-word forms of models to be generated. Publishing a HTML form of the class models of databse
          code is a great way of maintaining code documentation, without having to trouble developers.

      */


  -- init
  procedure
    init (
      /*
          Data-interfaces have dependencies on certain views, synonyms and privileges.  This proc executes the DDL to create 
          those dependencies.  It can also be used to remove them.  The pMode argument (either "Create" or "Drop") together
          with the pEntity argument ("DefaultObjectsAndPrivs", "Views", "PublicSynonyms",

          "PrivateSynonyms" or "Privs") is used to create or drop dependencies

          -- In most instances this proc (executed by a DBA) is sufficient
          xxschema."xxpub2".init('Create', 'DefaultObjectsAndPrivs' , :pOWNER);

          -- If public synonyms are not allowed
          -- Where :pOWNER is the database user that owns the data-interface and :pUSER is the user that will execute the data-interface

          xxschema."xxpub2".init('Create', 'Views' , :pOWNER);
          xxschema."xxpub2".init('Create', 'PrivateSynonyms' , :pUSER);
          xxschema."xxpub2".init('Create', 'Privs' , :pUSER);

          -- If that still does not work, get all the DDL and execute it manually (use either public or private synonyms, not both)
          xxschema."xxpub2".init('Create', 'Views' , :pOWNER, 'PrintDdl');
          xxschema."xxpub2".init('Create', 'PublicSynonyms' , :pOWNER, 'PrintDdl');
          xxschema."xxpub2".init('Create', 'PrivateSynonyms' , :pUSER, 'PrintDdl');
          xxschema."xxpub2".init('Create', 'Privs' , :pUSER ,'PrintDdl');

           -- If the data-interface is to be dropped, to ensure no orphaned dependencies, try
          xxschema."xxpub2".init('Drop' , 'DefaultObjectsAndPrivs' , 'xxschema');

      */
          pMode      varchar2              -- {"Create", "Drop"}
        , pEntity    varchar2 default null -- {"DefaultObjectsAndPrivs", "Views", "PublicSynonyms", "PrivateSynonyms", "Privs"}
        , pUser      varchar2 default null -- When pEntity is {"Privs"} then pUser should be set to the database user that will execute the 
                                           -- data-interface
                                           -- When pEntity is {"DefaultObjectsAndPrivs", "Views", "PrivateSynonyms"}  then pUser should
                                           -- be set to the owner of the data-interface
                                           -- When pEntity is {"PubicSynonyms"}  pUser is ignored
        , pPrintDdl  varchar2 default null -- {"PrintDdl", ""}
                                           -- When set to "PrintDdl" any DDL that would usually be executed is printed instead
    )
  ;

  g1number number                        := null;
  g2number number                        := null;

  type fn4Rec is record (F1  number, F2  varchar2(32), F3  varchar2(1024));
  type fn4Tab is table of fn4Rec;



  -- fn4
  function
    fn4 (
        /*
          Wrapper that allows the results of fn4RefC() to be fetched using the form ::

              select
                    *
              from
                    fn4
              where
                    xxschema."xxpub2".Setfn4(p1 => ??, p2 => ??) = 1 ;

          Note the use of the conjunctive function Setfn4()

          Allows the function to be executed over a database link ::

              select
                    *
              from
                    fn4@dblink
              where
                    xxschema."xxpub2".Setfn4@dblink(p1 => ??, p2 => ??) = 1

          Sets filtering criteria (by setting package global variables for the session). Always returns "1"


        */
          p1                                          number   := g1  --Description of parameter p1
        , p2                                          number   := g2  --Description of parameter p2
    )
      return
        fn4Tab pipelined
  ;


  -- fn4
  function
    fn4 (
        /*
          Strong-type wrapper for fn4RefC() that allows the form ::

              select
                    *
              from
                    xxschema."xxpub2".fn4(
                          xxschema."xxpub2".fn4RefC(
                                p1 => ??, p2 => ??
                          )
                    )
              ;

          Because this function returns a pipe-lined function it can not be called over a database link.


        */
          pCursor      sys_refcursor
    )
      return
        fn4Tab pipelined
  ;


  -- fn4RefC
  function
    fn4RefC (
      /* 
        functional description of fn3
      */

      /* 
        Returns a ref-cursor, which when executed returns records in the form ::
        
        COLUMN                        TYPE          DESCRIP                         
        ----------------------------  ------------  --------------------------------
        F1                            (Integer)                                     
        F2                            (String)                                      
        F3                            (String)                                      

        Following is an example of calling this function in PL/SQL ::

        declare
          vRow xxschema."xxpub2".fn4Rec
          vCursor sys_refcursor;
        begin
          pCursor :=
                fn4RefC (
                    p1 => ??
                  , p2 => ??
                );
          loop
              fetch pCursor into vRow;
              exit when pCursor%notfound;
              -- Do useful stuff
          end loop;
          close pCursor;
        end;
      */
          p1                                          number    --Description of parameter p1
        , p2                                          number    --Description of parameter p2
    )
      return
        sys_refcursor
  ;


  -- Setfn4
  function
    Setfn4 (
      /* 
        Following is an example of calling this function in PL/SQL ::
            select
                  *
            from
                  fn4
            where
                  xxschema."xxpub2".Setfn4(
                    p1 => ??, p2 => ??
                  ) = 1
        ;

        Sets filtering criteria (by setting package global variables for the session). Always returns "1".

        Developer NOTE: This function is generated to work closely with fn4RefC(). It is intended that only fn4RefC() should be
        customized, and this function should not be modified from its generated form.
      */
          p1                                          number    --Description of parameter p1
        , p2                                          number    --Description of parameter p2
    )
      return
        number
  ;


  -- fn5
  function
    fn5 (
      /* 
        functional description of fn3
      */

          p1                                          number    --Description of parameter p1
    )
      return
        M01.v02.fn5_rectype 
  ;

end;
/
