create or replace package xxschema1."xxPub3"
as
      /*
        Package level documentation (from the class description of the DB Package)
      */

      /*
        Generated by "OraDbCodeGen", a Visual Paradigm plugin that allows database code to be modeled using
        UML Class diagram models. Implements a "data-interface", allowing upstream systems (such as
        middlware backends) to access specific data sets without exposing any part of the underlying data
        model. Instead of direct access to any database tables, "ref-cursor" functions are provided that
        return ref-cursors. This implementation keeps the database query logic private from any upsteam
        systems.

        Ref-cursors work with coding languages that do not require strong typing, such as Java, Go, etc.
        When the upstream system is another database system, such as over a database link, strongly-typed
        access is needed (ref-cursors do not work over database links). For each "ref-cursor" function, a
        set of wrapper functions are provided that allow for "strongly-typed" access.

        "OraDbCodeGen" automates the creation of the "ref-cursor" functions and their "strongly-typed"
        wrapper functions by generating database code from a UML class model. The UML class model must
        implement certain specific conventions and stereotypes as the means of specifying "ref-cursor"
        functions. "OraDcCodeGen" also allows the generation of generic procs, functions and packages that
        do not need to implement a "data-interface" for upstream systems.

        Asides from the utility of the "ref-cursor" and "stongly-typed" wrapper functionality offered by
        "OraDbCodeGen", creating a UML model of one's database code is a practice that has significant
        advantages:

          1. Speeds up the process of developing and maintaining database code (yes, detailed documentation -
          especially up front - speeds things up).

          2. Class diagram models provide an excellent, and very granular form of specification, allowing the
          code's designers to communicate to the code's developers what to code.

          3. Allows the concerns of the code's designers (what procs and functions are needed, what should
          their arguments be, how do they interact with one another) to be separated from the concerns of the
          code's developers (what is the best code to achieve the functionality).

          4. UML class models of database code are visually compact, and easy to work with. They allow code
          designers to model code bases that can get very large, consisting of hundreds or thousands of
          procedures and functions. It is a simple matter to maintain one version of the model representing
          the current state of the code, and other versions representing future states of the code, which
          form the specifications that developers later use to change the code.


        So using UML models of database code have their advantages. Creating those models in Visual
        Paradigm, together with using the "OraDbCodeGen" plugin has further advantages, over and above the
        "data-interface" capabilities:

          5. When a UML class model is used in conjunction with a plugin like this one, an initial 'stub' of
          the code can be generated from the model in seconds, giving developers a headstart.

          6. Generating the initial code from a model allows the element descriptions in the model to be
          included as "documentation" within the generated code.

          7. Documentation can be generated from the model. In particular, Visual Paradigm allows for HTML
          and MS-word forms of models to be generated. Publishing a HTML form of the class models of databse
          code is a great way of maintaining code documentation, without having to trouble developers.

      */


  -- init
  procedure
    init (
      /*
          Data-interfaces have dependencies on certain views, synonyms and privileges.  This proc executes the DDL to create
          those dependencies.  It can also be used to remove them.  The pMode argument (either "Create" or "Drop") together
          with the pEntity argument ("DefaultObjectsAndPrivs", "Views", "PublicSynonyms",

          "PrivateSynonyms" or "Privs") is used to create or drop dependencies

          -- In most instances this proc (executed by a DBA) is sufficient
          xxschema1."xxPub3".init('Create', 'DefaultObjectsAndPrivs' , :pOWNER);

          -- If public synonyms are not allowed
          -- Where :pOWNER is the database user that owns the data-interface and :pUSER is the user that will execute the data-interface

          xxschema1."xxPub3".init('Create', 'Views' , :pOWNER);
          xxschema1."xxPub3".init('Create', 'PrivateSynonyms' , :pUSER);
          xxschema1."xxPub3".init('Create', 'Privs' , :pUSER);

          -- If that still does not work, get all the DDL and execute it manually (use either public or private synonyms, not both)
          xxschema1."xxPub3".init('Create', 'Views' , :pOWNER, 'PrintDdl');
          xxschema1."xxPub3".init('Create', 'PublicSynonyms' , :pOWNER, 'PrintDdl');
          xxschema1."xxPub3".init('Create', 'PrivateSynonyms' , :pUSER, 'PrintDdl');
          xxschema1."xxPub3".init('Create', 'Privs' , :pUSER ,'PrintDdl');

           -- If the data-interface is to be dropped, to ensure no orphaned dependencies, try
          xxschema1."xxPub3".init('Drop' , 'DefaultObjectsAndPrivs' , 'xxschema1');

      */
          pMode      varchar2              -- {"Create", "Drop"}
        , pEntity    varchar2 default null -- {"DefaultObjectsAndPrivs", "Views", "PublicSynonyms", "PrivateSynonyms", "Privs"}
        , pUser      varchar2 default null -- When pEntity is {"Privs"} then pUser should be set to the database user that will execute the
                                           -- data-interface
                                           -- When pEntity is {"DefaultObjectsAndPrivs", "Views", "PrivateSynonyms"}  then pUser should
                                           -- be set to the owner of the data-interface
                                           -- When pEntity is {"PubicSynonyms"}  pUser is ignored
        , pPrintDdl  varchar2 default null -- {"PrintDdl", ""}
                                           -- When set to "PrintDdl" any DDL that would usually be executed is printed instead
    )
  ;

  g1number                         := null;
  g2varchar2(4000)                 := null;

  type pv2Rec is record (F1  varchar2(32), F2  number, F3  number);
  type pv2Tab is table of pv2Rec;

  type pv1Rec is record (F1  varchar2(32), F2  number, F3  number);
  type pv1Tab is table of pv1Rec;



  -- pr1
  procedure
    pr1 (
      /*
        Document the pr1 procedure here. This is an ordinary procedure, with no outputs.
      */
          p1                                          varchar2
    )
  ;


  -- fn1
  function
    fn1 (
      /*
        Document fn1 here. This is an ordinary function, returning a number.
      */

          p1                                          number
        , p2                                          number
    )
      return
        number
  ;


  -- pv2
  function
    pv2 (
        /*
          Wrapper that allows the results of pv2RefC() to be fetched using the form ::

              select
                    *
              from
                    pv2
              where
                    xxschema1."xxPub3".Setpv2(p1 => ??, p2 => ??) = 1 ;

          Note the use of the conjunctive function Setpv2()

          Allows the function to be executed over a database link ::

              select
                    *
              from
                    pv2@dblink
              where
                    xxschema1."xxPub3".Setpv2@dblink(p1 => ??, p2 => ??) = 1

          Sets filtering criteria (by setting package global variables for the session). Always returns "1"


        */
          p1                                          number   := g1
        , p2                                          varchar2 := g2
    )
      return
        pv2Tab pipelined
  ;


  -- pv2
  function
    pv2 (
        /*
          Strong-type wrapper for pv2RefC() that allows the form ::

              select
                    *
              from
                    xxschema1."xxPub3".pv2(
                          xxschema1."xxPub3".pv2RefC(
                                p1 => ??, p2 => ??
                          )
                    )
              ;

          Because this function returns a pipe-lined function it can not be called over a database link.


        */
          pCursor      sys_refcursor
    )
      return
        pv2Tab pipelined
  ;


  -- pv2RefC
  function
    pv2RefC (        Returns a ref-cursor, which when executed returns records in the form ::

        COLUMN                        TYPE          DESCRIP
        ----------------------------  ------------  --------------------------------
        F1                            (String)
        F2                            (Integer)
        F3                            (Integer)

        Following is an example of calling this function in PL/SQL ::

        declare
          vRow xxschema1."xxPub3".pv2Rec
          vCursor sys_refcursor;
        begin
          pCursor :=
                pv2RefC (
                    p1 => ??
                  , p2 => ??
                );
          loop
              fetch pCursor into vRow;
              exit when pCursor%notfound;
              -- Do useful stuff
          end loop;
          close pCursor;
        end;
          p1                                          number
        , p2                                          varchar2
    )
      return
        sys_refcursor
  ;


  -- Setpv2
  function
    Setpv2 (
      /*
        Following is an example of calling this function in PL/SQL ::
            select
                  *
            from
                  pv2
            where
                  xxschema1."xxPub3".Setpv2(
                    p1 => ??, p2 => ??
                  ) = 1
        ;

        Sets filtering criteria (by setting package global variables for the session). Always returns "1".

        Developer NOTE: This function is generated to work closely with pv2RefC(). It is intended that only pv2RefC() should be
        customized, and this function should not be modified from its generated form.
      */
          p1                                          number
        , p2                                          varchar2
    )
      return
        number
  ;


  -- pv1
  function
    pv1 (
        /*
          Wrapper that allows the results of pv1RefC() to be fetched using the form ::

              select
                    *
              from
                    pv1
              where
                    xxschema1."xxPub3".Setpv1(p1 => ??, p2 => ??) = 1 ;

          Note the use of the conjunctive function Setpv1()

          Allows the function to be executed over a database link ::

              select
                    *
              from
                    pv1@dblink
              where
                    xxschema1."xxPub3".Setpv1@dblink(p1 => ??, p2 => ??) = 1

          Sets filtering criteria (by setting package global variables for the session). Always returns "1"


        */
          p1                                          number   := g1
        , p2                                          varchar2 := g2
    )
      return
        pv1Tab pipelined
  ;


  -- pv1
  function
    pv1 (
        /*
          Strong-type wrapper for pv1RefC() that allows the form ::

              select
                    *
              from
                    xxschema1."xxPub3".pv1(
                          xxschema1."xxPub3".pv1RefC(
                                p1 => ??, p2 => ??
                          )
                    )
              ;

          Because this function returns a pipe-lined function it can not be called over a database link.


        */
          pCursor      sys_refcursor
    )
      return
        pv1Tab pipelined
  ;


  -- pv1RefC
  function
    pv1RefC (
      /*
        df1 is special, because:

         1. it is modeled to return a class, and
         2. the class has stereotype 'OracleDbRecType'.

        On account of those two special features, instead of an ordinary procedure being generated into the resulting database
        package, a set of specially forms procedures will included in the database package. Taken together, those procedures
        provide an approximation of a parameterized view. The documentation generated into the resulting package specification
        gives full details.
      */

      /*
        Returns a ref-cursor, which when executed returns records in the form ::

        COLUMN                        TYPE          DESCRIP
        ----------------------------  ------------  --------------------------------
        F1                            (String)
        F2                            (Integer)
        F3                            (Integer)

        Following is an example of calling this function in PL/SQL ::

        declare
          vRow xxschema1."xxPub3".pv1Rec
          vCursor sys_refcursor;
        begin
          pCursor :=
                pv1RefC (
                    p1 => ??
                  , p2 => ??
                );
          loop
              fetch pCursor into vRow;
              exit when pCursor%notfound;
              -- Do useful stuff
          end loop;
          close pCursor;
        end;
      */
          p1                                          number
        , p2                                          varchar2
    )
      return
        sys_refcursor
  ;


  -- Setpv1
  function
    Setpv1 (
      /*
        Following is an example of calling this function in PL/SQL ::
            select
                  *
            from
                  pv1
            where
                  xxschema1."xxPub3".Setpv1(
                    p1 => ??, p2 => ??
                  ) = 1
        ;

        Sets filtering criteria (by setting package global variables for the session). Always returns "1".

        Developer NOTE: This function is generated to work closely with pv1RefC(). It is intended that only pv1RefC() should be
        customized, and this function should not be modified from its generated form.
      */
          p1                                          number
        , p2                                          varchar2
    )
      return
        number
  ;

end;
/

